let shopItemsData = [
  {
    id: "sdadas",
    name: "Blue Artisan",
    price: 2536,
    desc: "Casual",
    img: "../images/blue1.webp",
  },
  {
    id: "dfgdfgf",
    name: "Nike React Infinity Run Flyknit",
    price: 3122,
    desc: "RUNNING",
    img: "../images/1nike.webp",
  },
  {
    id: "ioytrhndcv",
    name: "Sky Dance",
    price: 3879,
    desc: "Casual",
    img: "../images/blue2.webp",
  },
  {
    id: "sewdrsedf",
    name: "Nike React Miler",
    price: 5100,
    desc: "RUNNING",
    img: "../images/2nike.webp",
  },
  {
    id: "thyfhcbcv",
    name: "Mcbeth Blue",
    price: 5236,
    desc: "Casual",
    img: "../images/cyan1.png",
  },
  {
    id: "sdfsdfsdfjh",
    name: "Nike Air Zoom Pegasus 37",
    price: 3411,
    desc: "RUNNING",
    img: "../images/3nike.webp",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Light Dusk",
    price: 5100,
    desc: "Casual",
    img: "../images/cyan2.png",
  },
  {
    id: "okjlfghdf",
    name: "Nike Joyride Run Flyknit",
    price: 5236,
    desc: "RUNNING",
    img: "../images/4nike.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Green Hornet",
    price: 3411,
    desc: "Casual",
    img: "../images/Green1.webp",
  },
  {
    id: "aseqwewq",
    name: "Nike Mercurial Vapor 13 Elite FG",
    price: 4750,
    desc: "FOOTBALL",
    img: "../images/5nike.webp",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Maple Green",
    price: 8750,
    desc: "Casual",
    img: "../images/Green2.webp",
  },
  {
    id: "pljikolygj",
    name: "Nike Phantom Vision Elite Dynamic Fit FG",
    price: 4760,
    desc: "FOOTBALL",
    img: "../images/6nike.webp",
  },
  {
    id: "sdfdsflo",
    name: "Marble White",
    price: 5470,
    desc: "Casual",
    img: "../images/obsidian1.png",
  },
  {
    id: "wefseaf",
    name: "Nike Phantom Venom Academy FG",
    price: 6300,
    desc: "FOOTBALL",
    img: "../images/7nike.webp",
  },
  {
    id: "ertxcvjh",
    name: "Neon Light",
    price: 3510,
    desc: "Casual",
    img: "../images/orange1.webp",
  },
  {
    id: "ouihuk",
    name: "Nike Mercurial Vapor 13 Elite Tech Craft FG",
    price: 3560,
    desc: "FOOTBALL",
    img: "../images/8nike.webp",
  },
  {
    id: "pfghawse",
    name: "Tangerine Isle",
    price: 3890,
    desc: "Casual",
    img: "../images/orange2.png",
  },
  {
    id: "sersr",
    name: "Nike Mercurial Superfly 7 Pro MDS FG",
    price: 3250,
    desc: "FOOTBALL",
    img: "../images/9nike.webp",
  },
  {
    id: "ervjs",
    name: "Delube Grey",
    price: 3500,
    desc: "Casual",
    img: "../images/purple1.webp",
  },
  {
    id: "piujhujk",
    name: "Nike Air Force 1",
    price: 3500,
    desc: "Casual",
    img: "../images/10nike.webp",
  },
  {
    id: "ecjfg",
    name: "Resistance Purple",
    price: 3500,
    desc: "Casual",
    img: "../images/purple2.webp",
  },
  {
    id: "qawerwq",
    name: "Nike Air Max 90",
    price: 3500,
    desc: "Casual",
    img: "../images/11nike.webp",
  },
  {
    id: "phgsan",
    name: "Valorant Team",
    price: 3800,
    desc: "Casual",
    img: "../images/purple3.webp",
  },
  {
    id: "oiuyutg",
    name: "Nike Air Max 90 LTR",
    price: 3800,
    desc: "Casual",
    img: "../images/12nike.webp",
  },
  {
    id: "sdfdsfsf",
    name: "Color me Red",
    price: 3520,
    desc: "Casual",
    img: "../images/rainbow1.webp",
  },
  {
    id: "efgvsdcvxz",
    name: "Nike Joyride Dual Run",
    price: 3550,
    desc: "RUNNING",
    img: "../images/13nike.webp",
  },
  {
    id: "kjihkgyh",
    name: "Bring me Rainbow",
    price: 3590,
    desc: "Casual",
    img: "../images/rainbow2.webp",
  },
  {
    id: "uyighfvnvgbh",
    name: "Nike Renew Run",
    price: 3570,
    desc: "RUNNING",
    img: "../images/14nike.webp",
  },
  {
    id: "asdas",
    name: "Rainbow Drop",
    price: 3530,
    desc: "Casual",
    img: "../images/rainbow3.webp",
  },
  {
    id: "hjgjghj",
    name: "Golden Sabas",
    price: 3560,
    desc: "Casual",
    img: "../images/worn1.webp",
  },
  {
    id: "sdafsdfgds",
    name: "Brighter than the Sun",
    price: 3590,
    desc: "Casual",
    img: "../images/yellow1.webp",
  },
  {
    id: "fdgdfg",
    name: "Sunny Tan",
    price: 3400,
    desc: "Casual",
    img: "../images/yellow2.webp",
  },
];
